### ISSUE TITLE
Only 1 game showing

### ISSUE THREAD

**Issue by rickgaiser** [brainstream/OPL-PC-Tools#1]
In the main window only 1 game is shown. When I remove that game, another 2 games are shown. Then when I remove those 2 games, nothing shows up anymore. There should have been a large list of games.

I've tested the linux version, and also compiled the latest sources. The problem was the same in both.

**Comment by brainstream** [comment]
Thanks for reporting the issue. I'll investigate the problem.

PS. Thank you for using OPL PC Tools!

**Comment by rickgaiser** [comment]
Thank you for creating this. I was really missing a program like this on Linux.

I don't have much time, but if there's anything I can do to help debug this problem please let me know.

**Comment by brainstream** [comment]
Hi @rickgaiser!
I'm trying to reproduce the issue but without results. Can you please tell me how your games are stored? If it is possible, can you show me your ul.cfg file and contents (`ls`) of the CD and DVD directories?

**Comment by TnA-Plastic** [comment]
@rickgaiser: I suppose you have missed his reply? ;)

**Comment by cosmincrihan** [comment]
I have the same issue, my games are stored using OPL Manager in a Windows virtual machine, but I suppose the folder and naming conventions are the same, right?
I have over 40 games in my collection and only 7 of them are showing.

**Comment by brainstream** [comment]
Hi @cosmincrihan!
Can you provide `ul.cfg` and a list of filenames in the CD and DVD directories?

**Comment by cosmincrihan** [comment]
Hey, @brainstream! Sure.
My `ul.cfg` file is empty (I don't exactly know why), and I can provide you the structure of my PS2 library:

- the `CD` folder has the following games:
```'SLES_500.74.Unreal Tournament.iso'
'SLES_501.26.Quake III - Revolution.iso'
'SLES_501.86.Heroes of Might and Magic QftDBS.iso'
'SLES_502.82.AoE 2 - The Age of Kings.iso'
'SLES_505.04.Half Life.iso'
'SLES_511.92.Harry Potter 2 - CoS.iso'
'SLES_516.23.The Sniper 2.iso'
'SLES_536.39.Ford Street Racing.iso'
'SLES_545.49.Crazy Frog Racer 2.iso'
SLPM_621.76.EGBROWSER.iso```

- the `DVD` folder has the following games:
```'SCES_511.59.The Getaway.iso'
SCES_520.04.Killzone.iso
'SCES_531.33.God of War.iso'
'SCES_532.02.Tekken 5.iso'
'SCES_533.00.SOCOM 3.iso'
'SCES_540.94.EyeToy Play Sports.iso'
'SCES_542.06.God of War 2.iso'
'SCES_542.19.Buzz Junior - Jungle Party.iso'
'SLES_503.25.Max Payne.iso'
'SLES_503.30.Grand Theft Auto III.iso'
'SLES_503.58.Devil May Cry.iso'
'SLES_506.06.State of Emergency.iso'
'SLES_509.02.Conflict - Desert Storm.iso'
'SLES_510.61.Grand Theft Auto - Vice City.iso'
'SLES_514.34.Silent Hill 3.iso'
SLES_514.36.Chessmaster.iso
SLES_514.74.BloodRayne.iso
'SLES_515.23.Conflict - Desert Storm II.iso'
'SLES_519.67.Need for Speed - Underground.iso'
SLES_520.23.Manhunt.iso
'SLES_520.55.Harry Potter 1 - PS.iso'
'SLES_521.49.Tom Clancys Splinter Cell - PT.iso'
'SLES_522.14.The Haunted Mansion.iso'
'SLES_522.88.Tom Clancys Rainbow Six 3.iso'
'SLES_523.94.UEFA Euro 2004 Portugal.iso'
SLES_524.51.Conan.iso
'SLES_524.80.Yu-Gi-oh TDotR.iso'
'SLES_525.27.Harry Potter 3 - PoA.iso'
'SLES_525.36.DreamWorks Shark Tale.iso'
'SLES_525.41.Grand Theft Auto - San Andreas.iso'
'SLES_525.84.Burnout 3 - Takedown.iso'
'SLES_527.25.Need for Speed - Underground 2.iso'
'SLES_528.84.Duel Masters.iso'
'SLES_530.38.Devil May Cry 3 - DA.iso'
'SLES_535.29.FIFA 06.iso'
'SLES_535.57.Need for Speed - Most Wanted.iso'
'SLES_537.02.Resident Evil 4.iso'
'SLES_537.26.Harry Potter 4 - GoF.iso'
SLES_537.78.Jacked.iso
'SLES_542.40.FIFA 07.iso'
'SLES_542.45.NHL 07.iso'
'SLES_543.21.Need for Speed - Carbon.iso'
'SLES_544.42.Guitar Hero II.iso'
'SLES_546.74.Tomb Raider - Anniversary.iso'
'SLES_547.79.Harry Potter 5 - OotP.iso'
'SLES_550.02.Need for Speed - ProStreet.iso'
'SLES_552.48.Harry Potter 6 - HBP.iso'
'SLES_554.52.Shaun White Snowboarding.iso'
'SLES_556.42.FIFA 11.iso'
'SLES_820.09.Metal Gear Solid 2 - Substance.iso'
'SLES_820.13.Metal Gear Solid 3 - Snake Eater.iso'```

I also attach a "tree" command output, if it helps you more in identifying the issue, so you can see the complete folder library.
[PS2_LIBRARY_TREE.log](https://github.com/brainstream/OPL-PC-Tools/files/5148726/PS2_LIBRARY_TREE.log)

**Comment by cosmincrihan** [comment]
I forgot to mention the games that do show up, maybe this would help too. I attach a screenshot here.
![Screenshot_2020-08-31_09-52-47](https://user-images.githubusercontent.com/42542634/91691131-c9566100-eb6f-11ea-9ad1-caec81c7ebf2.png)

**Comment by brainstream** [comment]
Thank! I'll try to figure out the problem. But I don't have much time now. I guess I'll take a look at this this month.

**Comment by brainstream** [comment]
Hi @cosmincrihan!
I've just released the new version. It does not completely solve the problem. But I suppose you have one or more broken images. In the previous version, the loading stopped in this case. A newer version ignores the broken image and continues loading.

Please try to load your directory with the new version. There must be some images which can not be loaded. You can try to check them yourself. If you can't or they look like working images, send them to me please.

**Comment by cosmincrihan** [comment]
Thank you for addressing the issue, @brainstream, it is so much better now!
The only games that are not shown are as follows:

- Killzone (SCES_520.04.Killzone.iso)
- State of Emergency (SLES_506.06.State of Emergency.iso)
- Yu Gi Oh - The Duelist of the Roses (SLES_524.80.Yu-Gi-oh TDotR.iso)

I also notice some warnings when opening the tool from a separate terminal, but I assume they are not critical:
```
cosmin@debian-gl553v:/opt/oplpctools$ ./oplpctools.sh 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by brainstream** [comment]
Thank you @cosmincrihan!
I downloaded these files, you can delete them.
I reproduced the issue. I'll investigate the problem and let you know when I'll fix it.

**Comment by brainstream** [comment]
Good news! I fixed the issue. Please download the version 2.4.
