### ISSUE TITLE
Doesn't show games from iso

### ISSUE THREAD

**Issue by Dimsok** [brainstream/OPL-PC-Tools#11]
Noticed, that OPL-PC-Tools doens't show games from iso files (from DVD folder). Only from ul.cfg. Is it normal?

**Comment by brainstream** [comment]
Hi  Dimsok!

It isn't normal of course! I need more information to reproduce this issue. 

- What OS are you using?
- Which version of the OPL PC Tools are you using?
- Can you show a list of filenames in the DVD folder?
- Can you send me one of these files?

**Comment by Dimsok** [comment]
1. Windows XP.
2.  The last version.
3.  Later (not on my pc now).
4. Do you mean iso file of game? It's too big for my network. I just will try on other iso games.

**Comment by brainstream** [comment]
I just checked OPL PC Tools on Windows XP. Everything seems to be working correctly.

![opl-pc-tools-xp](https://user-images.githubusercontent.com/678778/118958224-e46d3900-b969-11eb-8531-557065a75679.png)

Thus, I believe that the root of the problem lies in specific files. It would be great if you could send me the ISO file. But if you can't, try with other ISOs and let me know the results.

**Comment by Dimsok** [comment]
The name of file is "Resident Evil - CODE Veronica X.iso".

**Comment by brainstream** [comment]
I tried using the image of this game. It works. You obviously have a different image.
Could you open the image with any archiver (7zip f/i) and extract a file called SYSTEM.CNF? What does it contain?

![iso](https://user-images.githubusercontent.com/678778/119350387-f0c5fe80-bca7-11eb-9a0e-0d1adfbe097f.PNG)

**Comment by Sai24tamil** [comment]
Can anyone say me where can I download ul.cfg file for ps2?!!

**Comment by anderson-as230** [comment]
> Can anyone say me where can I download ul.cfg file for ps2?!!

You should download ISO file game and converter to ul.cfg

**Comment by Sai24tamil** [comment]
I am just needed ul.cfg file not iso file...I downloaded dragon ball z
budokai tenkaichi 3 iso file on my pc but it's cfg file was accidentally
deleted so please send me the cfg file or say where can I download

**Comment by anderson-as230** [comment]
https://github.com/IsseiYoshida/OPLUtil

App run windows yet

**Comment by Sai24tamil** [comment]
Bro what am I do with this link?
