### ISSUE TITLE
[FR] force copy without fragmentation

### ISSUE THREAD

**Issue by eadmaster** [brainstream/OPL-PC-Tools#12]
Not sure if doable, but it would be nice to have an option to copy without fragmentation, or to defrag in 1 piece **after** copying a new game.

**Comment by brainstream** [comment]
If I understand you correctly, there are all features you are described.

To install a game without fragmentation check the "Do not split up ISO file" option.

![image](https://user-images.githubusercontent.com/678778/127440753-fb620e02-4556-4408-928b-a30185d69f7a.png)

To restore a fragmented game to an ISO file use the "Restore ISO" button.

![image](https://user-images.githubusercontent.com/678778/127440859-9ee8f1c8-14aa-4686-adb7-fc159af994b2.png)

**Comment by eadmaster** [comment]
no sorry, i meant [file-system level fragmentation preventing a game from booting](https://www.reddit.com/r/ps2/comments/gfqntr/oplgame_is_fragmented/)..

**Comment by brainstream** [comment]
Thanks for the clarification! I have no control over the FS writing process. It is controlled by the OS. I can not do anything.
