### ISSUE TITLE
Won't boot for me on Windows 10 Home Edition

### ISSUE THREAD

**Issue by TheSteveEXNEO** [brainstream/OPL-PC-Tools#13]
Howdy.  I've been trying to get this program to work on my Windows 10 machine, and, for the life of me, I can't get it to start.  I've tried running it as an administrator and running it in compatibility mode for everything from XP Service Pack 2 to 8, at it won't start.  I try to run the exe, and nothing happens.  If I've checked some of the compatibility stuff off beforehand, I might get that window from Windows asking to check what's wrong, and that's it.  I downloaded the the tarball on my Linux Mint machine, and it'll start up just fine.  I think the issue might be with some security settings, but I don't know what exactly is preventing it from running on my main computer.

Just to get some tech junk on here:
Windows 10 Home Edition (64 bit)
Runs Microsoft Defender for antivirus
I'm pretty sure tried every version, but I can't quite remember; it's been a few days.  I've tried several, at least.

I run exe files I download from the internet all the time, so I know it's not just windows being set to block stuff not from the Microsoft Store.

Anyhow, in the meantime, I'll probably just use it on my Mint machine.

**Comment by brainstream** [comment]
Hello!
I've no idea what the problem is. I just tested the application is running on two Windows machines. Everything is working correctly. It looks like this is your local problem.
