### ISSUE TITLE
Add support to convert .bin and .cue to .iso

### ISSUE THREAD

**Issue by brunodavi** [brainstream/OPL-PC-Tools#18]
I discovered a command-line tool called 'bchunk' that converts .bin and .cue to PS2 .iso. If possible, could you add support for these files when installing .bin or .cue? Thank you.

**Comment by brainstream** [comment]
Hello!

OPL PC Tools already suppots a game installation from the `*.bin` files. The `*.cue` files need for multi-track images. I believe there are no PS2 images that use this feature. Thus you can just install a game from a *.bin` file.

**Comment by brunodavi** [comment]
Sorry, I didn't know that 😅
