### ISSUE TITLE
ul.cfg gets deleted

### ISSUE THREAD

**Issue by F1ReB4LL** [brainstream/OPL-PC-Tools#2]
When I remove any of the installed games, the whole ul.cfg gets deleted.

**Comment by brainstream** [comment]
Could you provide me a copy of your up.cfg? Also, please tell me which operating system are you using.

**Comment by F1ReB4LL** [comment]
OS is Win7 SP1 x64.
[ul.zip](https://github.com/brainstream/OPL-PC-Tools/files/2385691/ul.zip)
![ops2lpt_1](https://user-images.githubusercontent.com/39680140/45586435-1055d800-b900-11e8-99b4-2ff64e436437.png)
![ops2lpt_2](https://user-images.githubusercontent.com/39680140/45586437-151a8c00-b900-11e8-813c-e69fe3a1ffdd.png)

**Comment by brainstream** [comment]
I've published version with fix of this issue. Try it https://github.com/brainstream/OPL-PC-Tools/releases/tag/2.1
