### ISSUE TITLE
Build on macOS

### ISSUE THREAD

**Issue by beogivaljr** [brainstream/OPL-PC-Tools#5]
Hi, sorry if it shouldn't be an issue but I was wondering how can I build OPL PC Tools on MacOS

**Comment by brainstream** [comment]
Hi
I'm not a MacOS user. I don't have a Mac machine. But I believe you can build OPL PC Tools yourself.

- The first thing you need to do is to download [Qt Creator open source edition](https://www.qt.io/download).
- In Qt Creator, use the File -> Open File of Project menu.
- Navigate to the OPL PC Tools source code directory and select the CMakeLists.txt file
- You can leave the default settings in the Configure Project dialog and click the Configure Project button.
- Select the Minimal Size Release build type.
  ![image](https://user-images.githubusercontent.com/678778/106422579-e7522580-646f-11eb-830f-162d54e856a9.png)
- Next, you need to click the Build button (hammer icon).
- After the build is complete, the executable file must be placed in the directory specified in one of the last messages on the Compile Output tab.
  ![image](https://user-images.githubusercontent.com/678778/106423116-db1a9800-6470-11eb-9469-8d33bb007891.png)
- Next, you need to collect all dependencies. It will probably be the same as in the Linux version. All of these libraries can be found in the Qt installation directory.
- Further steps are not clear to me. I don't know how to create a MacOS package file. Probably the program will work without it. ou probably need to copy and adapt the oplpctools.sh script to run the program. This script sets up environment variables to tell the OS where to look for shared libraries.

Some notes

- Download source code from [latest release](https://github.com/brainstream/OPL-PC-Tools/releases/), not from the repository
- MacOS X uses character devices to represent a CD/DVD drive. OPL PC Tools cannot read it. So you won't be able to read from the optical drive. This is a known issue.

Feel free to ask any further questions. And thank you for your interest in OPL PC Tools.
